In [1]:
import utils
import surprise
import divergences

In [2]:
list1= utils.pmi(["apple", "banana", "melon"])#, "banana", "apple", "melon"])
list2 =utils.pmi(["banana", "apple", "melon"])
dict1 = surprise.pmi_to_dict(list1)
dict2 = surprise.pmi_to_dict(list2)

print(dict1)
print(dict2)

{'apple': {'banana': 0.5849625007211562, 'melon': 0.5849625007211562}, 'banana': {'melon': 0.5849625007211562}, 'variables': ['banana', 'melon']}
{'apple': {'melon': 0.5849625007211562}, 'banana': {'apple': 0.5849625007211562, 'melon': 0.5849625007211562}, 'variables': ['melon', 'apple']}


In [95]:
import importlib
importlib.reload(utils)
importlib.reload(surprise)

<module 'surprise' from 'c:\\Users\\edgar\\OneDrive\\Bureau\\Ecole\\HEC\\A24\\BrevetNLP\\PatentNovelty\\novelty\\surprise.py'>

# problème get_common_vectors

In [127]:
list_pmi = [(("apple", "banana"), 1.2), (("apple", "cherry"), 0.8), (("banana", "cherry"), 1.5)]
list_pmi_new = [(("apple", "banana"), 1.1), (("apple", "grape"), 0.9), (("banana", "cherry"), 1.3), (("banana", "grape"), 1.0), (("cherry", "grape"), 0.7), (("apple", "melon"), 0.6)]

In [128]:
dict_pmi = surprise.pmi_to_dict(list_pmi)
dict_pmi_new = surprise.pmi_to_dict(list_pmi_new)

print("List: ", list_pmi)
print("Nested dict: ", dict_pmi)
print("")
print("List: ", list_pmi_new)
print("Nested dict: ", dict_pmi_new)

List:  [(('apple', 'banana'), 1.2), (('apple', 'cherry'), 0.8), (('banana', 'cherry'), 1.5)]
Nested dict:  {'apple': {'banana': 1.2, 'cherry': 0.8}, 'banana': {'cherry': 1.5}, 'variables': ['banana', 'cherry']}

List:  [(('apple', 'banana'), 1.1), (('apple', 'grape'), 0.9), (('banana', 'cherry'), 1.3), (('banana', 'grape'), 1.0), (('cherry', 'grape'), 0.7), (('apple', 'melon'), 0.6)]
Nested dict:  {'apple': {'banana': 1.1, 'grape': 0.9, 'melon': 0.6}, 'banana': {'cherry': 1.3, 'grape': 1.0}, 'cherry': {'grape': 0.7}, 'variables': ['banana', 'grape', 'cherry', 'melon']}


In [131]:
print("Nested dict: ", dict_pmi)
print("Nested new dict: ", dict_pmi_new)

Nested dict:  {'apple': {'banana': 1.2, 'cherry': 0.8}, 'banana': {'cherry': 1.5}, 'variables': ['banana', 'cherry']}
Nested new dict:  {'apple': {'banana': 1.1, 'grape': 0.9, 'melon': 0.6}, 'banana': {'cherry': 1.3, 'grape': 1.0}, 'cherry': {'grape': 0.7}, 'variables': ['banana', 'grape', 'cherry', 'melon']}


In [130]:
vecotr_tuples = surprise.Surprise(pmi_new=list_pmi_new).get_common_vectors(dict_old=dict_pmi, dict_new=dict_pmi_new, epsilon=0)

print("")
print("")
print("Vector tuples: ")
vecotr_tuples

inter_list:  ['melon', 'banana', 'cherry', 'grape']
entry:  melon
    [0, 0, 0, 0],    {}
    [0, 0, 0, 0],    {}
entry:  banana
    [0, 0, 1.5, 0],    {'cherry': 1.5}
    [0, 0, 1.3, 1.0],    {'cherry': 1.3, 'grape': 1.0}
entry:  cherry
    [0, 0, 0, 0],    {}
    [0, 0, 0, 0.7],    {'grape': 0.7}
entry:  grape
    [0, 0, 0, 0],    {}
    [0, 0, 0, 0],    {}


Vector tuples: 


{'melon': ([0, 0, 0, 0], [0, 0, 0, 0]),
 'banana': ([0, 0, 1.5, 0], [0, 0, 1.3, 1.0]),
 'cherry': ([0, 0, 0, 0], [0, 0, 0, 0.7]),
 'grape': ([0, 0, 0, 0], [0, 0, 0, 0])}

## Ajutement

In [82]:
dict_pmi2 = utils.pmi_to_dict2(list_pmi)
dict_pmi_new2 = utils.pmi_to_dict2(list_pmi_new)

print("List: ", list_pmi)
print("Nested dict: ", dict_pmi2)
print("")
print("List: ", list_pmi_new)
print("Nested dict: ", dict_pmi_new2)

List:  [(('apple', 'banana'), 1.2), (('apple', 'cherry'), 0.8), (('banana', 'cherry'), 1.5)]
Nested dict:  {'apple': {'banana': 1.2, 'cherry': 0.8}, 'banana': {'cherry': 1.5}, 'w1': ['apple', 'banana'], 'w2': ['banana', 'cherry']}

List:  [(('apple', 'banana'), 1.1), (('apple', 'grape'), 0.9), (('banana', 'cherry'), 1.3), (('banana', 'grape'), 1.0), (('cherry', 'grape'), 0.7), (('apple', 'melon'), 0.6)]
Nested dict:  {'apple': {'banana': 1.1, 'grape': 0.9, 'melon': 0.6}, 'banana': {'cherry': 1.3, 'grape': 1.0}, 'cherry': {'grape': 0.7}, 'w1': ['apple', 'banana', 'cherry'], 'w2': ['banana', 'grape', 'cherry', 'melon']}


In [ ]:
vecotr_tuples2 = surprise.Surprise(pmi_new=list_pmi_new).get_common_vectors2(dict_old=dict_pmi2, dict_new=dict_pmi_new2, epsilon=0)

print("")
print("")
print("Vector tuples: ")
vecotr_tuples

interList_w1:  ['banana', 'apple', 'cherry']
interList_w2:  ['melon', 'banana', 'cherry', 'grape']
entry:  banana
    [0, 0, 1.5, 0],    {'cherry': 1.5}
    [0, 0, 1.3, 1.0],    {'cherry': 1.3, 'grape': 1.0}
entry:  apple
    [0, 1.2, 0.8, 0],    {'banana': 1.2, 'cherry': 0.8}
    [0.6, 1.1, 0, 0.9],    {'banana': 1.1, 'grape': 0.9, 'melon': 0.6}
entry:  cherry
    [0, 0, 0, 0],    {}
    [0, 0, 0, 0.7],    {'grape': 0.7}


Vector tuples: 


{'banana': ([0, 0, 1.5, 0], [0, 0, 1.3, 1.0]),
 'apple': ([0, 1.2, 0.8, 0], [0.6, 1.1, 0, 0.9]),
 'cherry': ([0, 0, 0, 0], [0, 0, 0, 0.7])}

# Surprise

In [96]:
instanceSurprise = surprise.Surprise(pmi_new=list_pmi_new)
instanceSurprise2 = surprise.Surprise(pmi_new=list_pmi_new)

In [88]:
instanceSurprise.new_surprise(list_pmi, thr_surp=0)

[(('apple', 'grape'), 0.9), (('banana', 'grape'), 1.0), (('cherry', 'grape'), 0.7), (('apple', 'melon'), 0.6)]


(0.6666666666666666, 1)

In [97]:
instanceSurprise2.new_surprise(list_pmi, thr_surp=0)

[(('apple', 'grape'), 0.9), (('banana', 'grape'), 1.0), (('cherry', 'grape'), 0.7), (('apple', 'melon'), 0.6)]


(0.6666666666666666, 1)

In [126]:
instanceSurprise.uniq_surprise(dict_pmi, eps=0, thr_surp=0)

inter_list:  ['melon', 'banana', 'cherry', 'grape']
entry:  melon
    [0, 0, 0, 0],    {}
    [0, 0, 0, 0],    {}
entry:  banana
    [0, 0, 1.5, 0],    {'cherry': 1.5}
    [0, 0, 1.3, 1.0],    {'cherry': 1.3, 'grape': 1.0}
entry:  cherry
    [0, 0, 0, 0],    {}
    [0, 0, 0, 0.7],    {'grape': 0.7}
entry:  grape
    [0, 0, 0, 0],    {}
    [0, 0, 0, 0],    {}


(0.18127819858060748, 1)

In [125]:
instanceSurprise.uniq_surprise2(dict_pmi2, eps=0, thr_surp=0)

interList_w1:  ['banana', 'apple', 'cherry']
interList_w2:  ['melon', 'banana', 'cherry', 'grape']
entry:  banana
    [0, 0, 1.5, 0],    {'cherry': 1.5}
    [0, 0, 1.3, 1.0],    {'cherry': 1.3, 'grape': 1.0}
entry:  apple
    [0, 1.2, 0.8, 0],    {'banana': 1.2, 'cherry': 0.8}
    [0.6, 1.1, 0, 0.9],    {'banana': 1.1, 'grape': 0.9, 'melon': 0.6}
entry:  cherry
    [0, 0, 0, 0],    {}
    [0, 0, 0, 0.7],    {'grape': 0.7}


(0.26377072729350876, 1)

In [112]:
key_list = vecotr_tuples.keys() # directement interlist
key_list

dict_keys(['melon', 'banana', 'cherry', 'grape'])

In [117]:
entry = list(key_list)[1]
print(entry)
tuple_known = vecotr_tuples[entry][0]
tuple_new = vecotr_tuples[entry][1]

print("known: ", tuple_known)
print("new: ", tuple_new)
        
tuple_known = [max(0., val) for val in tuple_known]
tuple_new = [max(0., val) for val in tuple_new]   

print("known: ", tuple_known)
print("new: ", tuple_new)

banana
known:  [0, 0, 1.5, 0]
new:  [0, 0, 1.3, 1.0]
known:  [0.0, 0.0, 1.5, 0.0]
new:  [0.0, 0.0, 1.3, 1.0]


In [118]:
surprise_dists = []
if sum(tuple_known) != 0 and sum(tuple_new) != 0:   #### We can't compare to non existing vectors neither - si pmi négatif
    surprise_dists.append(divergences.Jensen_Shannon().JSDiv(tuple_known, tuple_new))

surprise_dists

[0.18127819858060748]

In [ ]:
from numpy.linalg import norm
from scipy.stats import entropy

P=  [0, 0, 1.5, 0]
Q=  [0, 0, 1.3, 1.0]

_P = P / norm(P, ord=1)
print(norm(P, ord=1))
print(_P)


_Q = Q / norm(Q, ord=1)
print(norm(Q, ord=1))
print(_Q)

_M = 0.5 * _P + 0.5 * _Q
print(_M)
print(entropy(_P, _M))
0.5 * entropy(_P, _M) + 0.5 * entropy(_Q, _M)

1.5
[0. 0. 1. 0.]
2.3
[0.         0.         0.56521739 0.43478261]
[0.        0.        0.7826087 0.2173913]
0.2451224580329849


0.18127819858060748